application/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'StaticPageController@index');
Route::get('/statistics', 'StatsController@index');

Route::get('/players', 'PlayerController@index');
Route::get('/players/search/{query}', 'PlayerController@search');
Route::post('/players/search', 'PlayerController@search');
Route::get('/players/{player}', 'PlayerController@show');

Route::get('/api', 'ApiController@index');
Route::get('/api/version', 'ApiController@version');
Route::get('/api/search-playername/{server?}/{query}', 'ApiController@searchPlayerName');
Route::get('/api/search-playername-all/{query}', 'ApiController@searchPlayerNameAll');

Route::group(array('prefix' => '/admin', 'middleware' => 'auth'), function() {
	Route::get('/players', 'PlayerAdminController@index');
	Route::get('/players/search', 'PlayerAdminController@search');
	Route::get('/players/{player}', 'PlayerAdminController@show');

	Route::resource('/servers', 'ServerController');
	Route::resource('/users', 'UserController');

	Route::get('/bans', 'PlayerBanController@index');
	Route::get('/bans/create/{player?}', 'PlayerBanController@create');
	Route::post('/bans', 'PlayerBanController@store');
	Route::get('/bans/{server}/{id}', 'PlayerBanController@edit');
	Route::put('/bans/{server}/{id}', 'PlayerBanController@update');
	Route::delete('/bans/{server}/{id}', 'PlayerBanController@destroy');

	Route::delete('/ban-records/{server}/{id}', 'PlayerBanRecordController@destroy');

	Route::get('/mutes', 'PlayerMuteController@index');
	Route::get('/mutes/create/{player?}', 'PlayerMuteController@create');
	Route::post('/mutes', 'PlayerMuteController@store');
	Route::get('/mutes/{server}/{id}', 'PlayerMuteController@edit');
	Route::put('/mutes/{server}/{id}', 'PlayerMuteController@update');
	Route::delete('/mutes/{server}/{id}', 'PlayerMuteController@destroy');

	Route::delete('/mute-records/{server}/{id}', 'PlayerMuteRecordController@destroy');

	Route::get('/notes', 'PlayerNoteController@index');
	Route::get('/notes/create/{player?}', 'PlayerNoteController@create');
	Route::post('/notes', 'PlayerNoteController@store');
	Route::get('/notes/{server}/{id}', 'PlayerNoteController@edit');
	Route::put('/notes/{server}/{id}', 'PlayerNoteController@update');
	Route::delete('/notes/{server}/{id}', 'PlayerNoteController@destroy');

	Route::get('/warnings', 'PlayerWarningController@index');
	Route::get('/warnings/create/{player?}', 'PlayerWarningController@create');
	Route::post('/warnings', 'PlayerWarningController@store');
	Route::get('/warnings/{server}/{id}', 'PlayerWarningController@edit');
	Route::put('/warnings/{server}/{id}', 'PlayerWarningController@update');
	Route::delete('/warnings/{server}/{id}', 'PlayerWarningController@destroy');

	Route::delete('/kicks/{server}/{id}', 'PlayerKickController@destroy');

	Route::get('/', 'AdminController@index');
	Route::get('/active-bans', 'AdminController@activeBans');
	Route::get('/active-mutes', 'AdminController@activeMutes');

	Route::get('/flush-cache', 'AdminController@flushCache');
	Route::get('/activity', 'AdminController@activity');

	Route::get('/config', 'ConfigurationController@index');
	Route::post('/config', 'ConfigurationController@update');
});

Route::group(array('prefix' => '/install', 'middleware' => 'install'), function() {
	Route::get('/', 'InstallController@index');
	Route::get('/config', 'InstallController@config');
	Route::post('/run', 'InstallController@install');
	Route::get('/finish', 'InstallController@finish');
});

Route::get('/home', function() {
	return redirect('/');
});

Route::controllers([
	'/auth/password' => 'Auth\PasswordController',
	'/auth' => 'Auth\AuthController',
]);

Route::bind('player', function($value)
{
	$id = uuid_to_id($value);
	$player = [];

	foreach(\App\Server::get() as $server) {
		$item = \App\Player::on($server->id)->find($id);
		if($item) array_push($player, $item);
	}

	if(count($player) <= 0)
		abort(404, 'Player not found.');
	
	return $player;
});

Route::bind('server', function($value)
{
	$server = \App\Server::find((int) $value);
	if(!$server) abort(404, 'Server not found.');

	return $server;
});

application/app/RecordBaseModel.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class RecordBaseModel extends Model {

	protected $appends = ['player_uuid', 'actor_uuid', 'created_at'];

	protected $hidden = ['player_id', 'actor_id'];

	protected $dates = ['created', 'updated', 'expires'];

	public $timestamps = false;

	public function getPlayerUuidAttribute()
	{	
		$this->attributes['player_uuid'] = id_to_uuid($this->attributes['player_id']);
		return $this->attributes['player_uuid'];
	}

	public function setPlayerUuidAttribute($value)
	{
		$this->attributes['player_uuid'] = $value;
		$this->attributes['player_id'] = uuid_to_id($value);
	}

	public function getActorUuidAttribute()
	{	
		$this->attributes['actor_uuid'] = id_to_uuid($this->attributes['actor_id']);
		return $this->attributes['actor_uuid'];
	}

	public function setActorUuidAttribute($value)
	{
		$this->attributes['actor_uuid'] = $value;
		$this->attributes['actor_id'] = uuid_to_id($value);
	}

	public function actor()
	{
		return $this->belongsToRelation('App\Player', 'actor_id');
	}

	public function player()
	{
		return $this->belongsToRelation('App\Player', 'player_id');
	}

	public function getCreatedAtAttribute() {
		return $this->created;
	}

	public function getOldAttribute() {
		return $this->created_at->diffInDays() >= 60;
	}

	public function getServerAttribute() {
		return \App\Server::find($this->getConnectionName())->name;
	}

	public function getServerIdAttribute() {
		return \App\Server::find($this->getConnectionName())->id;
	}

	public function setCreatedAttribute($value)
	{
		$this->attributes['created'] = $value->timestamp;
	}

	public function setUpdatedAttribute($value)
	{
		$this->attributes['updated'] = $value->timestamp;
	}

	public function setExpiresAttribute($value)
	{
		$this->attributes['expires'] = $value->timestamp;
	}

	public function getDurationAttribute()
	{	
		if($this->expires->timestamp == 0)
			return null;
		
		return $this->expires->diffForHumans($this->created, true);
	}

	/**
	 * A little bit of hacking to make Laravel work with multiple databases
	 */
	private function belongsToRelation($value1, $value2) {
		\Config::set('database.default', $this->getConnectionName());
		$relation = $this->belongsTo($value1, $value2);
		$relation->getRelated()->setConnection($this->getConnectionName());
		\Config::set('database.default', 'local');
		return $relation;
	}

}

application/resources/views/partials/activityItem.blade.php
@if(get_class($item) == "App\PlayerBan")
<a href="{{ url('/admin/bans/'.$item->serverId.'/'.$item->id) }}" class="list-group-item">
	<i class="fa fa-ban fa-fw"></i> {{ trans('app.newBan') }} ({{ $item->player->name }})
	<span class="pull-right text-muted small"><em>{{ $item->created->diffForHumans() }}</em>
	</span>
</a>
@elseif(get_class($item) == "App\PlayerBanRecord")
<a href="{{ url('/admin/players/'.$item->player->uuid) }}" class="list-group-item">
	<i class="fa fa-check fa-fw"></i> {{ ucfirst(trans('app.unbanned')) }} ({{ $item->player->name }})
	<span class="pull-right text-muted small"><em>{{ $item->created->diffForHumans() }}</em>
	</span>
</a>
@elseif(get_class($item) == "App\PlayerMute")
<a href="{{ url('/admin/mutes/'.$item->serverId.'/'.$item->id) }}" class="list-group-item">
	<i class="fa fa-microphone-slash fa-fw"></i> {{ trans('app.newMute') }} ({{ $item->player->name }})
	<span class="pull-right text-muted small"><em>{{ $item->created->diffForHumans() }}</em>
	</span>
</a>
@elseif(get_class($item) == "App\PlayerMuteRecord")
<a href="{{ url('/admin/players/'.$item->player->uuid) }}" class="list-group-item">
	<i class="fa fa-microphone fa-fw"></i> {{ ucfirst(trans('app.unmuted')) }} ({{ $item->player->name }})
	<span class="pull-right text-muted small"><em>{{ $item->created->diffForHumans() }}</em>
	</span>
</a>
@elseif(get_class($item) == "App\PlayerNote")
<a href="{{ url('/admin/notes/'.$item->serverId.'/'.$item->id) }}" class="list-group-item">
	<i class="fa fa-paperclip fa-fw"></i> {{ trans('app.newNote') }} ({{ $item->player->name }})
	<span class="pull-right text-muted small"><em>{{ $item->created->diffForHumans() }}</em>
	</span>
</a>
@elseif(get_class($item) == "App\PlayerWarning")
<a href="{{ url('/admin/warnings/'.$item->serverId.'/'.$item->id) }}" class="list-group-item">
	<i class="fa fa-comment fa-fw"></i> {{ trans('app.newWarning') }} ({{ $item->player->name }})
	<span class="pull-right text-muted small"><em>{{ $item->created->diffForHumans() }}</em>
	</span>
</a>
@elseif(get_class($item) == "App\PlayerKick")
<a href="{{ url('/admin/players/'.$item->player->uuid) }}" class="list-group-item">
	<i class="fa fa-user-times fa-fw"></i> {{ trans('app.newKick') }} ({{ $item->player->name }})
	<span class="pull-right text-muted small"><em>{{ $item->created->diffForHumans() }}</em>
	</span>
</a>
@endif

application/resources/views/partials/flash.blade.php
@if (session('message'))
<script>
	var dialog = BootstrapDialog.show({
		title: "{{ trans('app.notice') }}",
		message: "{{ session('message') }} @if (session('messageDetails'))<br /><br /><p>{{ trans('app.details') }}:<br />{{ session('messageDetails') }}</p>@endif",
		buttons: [{
			label: "{{ trans('app.ok') }}",
			action: function(dialog) {
				dialog.close();
			}
		}]
	});

	setTimeout(function() {
		dialog.close();
	}, 6000);
</script>
@endif

application/resources/views/partials/noscript.blade.php
<noscript>
	<div class="alert alert-box alert-warning">
	<strong>{{ trans('app.noJs') }}</strong><br />
	<p>{{ trans('app.noJsText') }}</p>
	</div>
</noscript>

application/resources/views/partials/recentPunishmentsTable.blade.php
@if(count($items) > 0)
<div class="table-responsive">
	<table class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<th>{{ trans('app.table.player') }}</th>
				<th>{{ trans('app.table.actor') }}</th>
				<th>{{ trans('app.table.created') }}</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach($items as $item)
				<tr>
					<td>{{ $item->player->name }}</td>
					<td>{{ $item->actor->name }}</td>
					<td>{{ $item->created_at->diffForHumans() }}</td>
					<td><a href="{{ url('/admin/players', $item->player->uuid) }}">{{ trans('app.details') }}</a></td>
				</tr>
			@endforeach
		</tbody>
	</table>
</div>
@else
<div class="alert alert-info">{{ trans('app.noData') }}</div>
@endif

application/resources/views/partials/timelineItem.blade.php
@if(get_class($item) == "App\PlayerBan")
<li class="timeline">
	<div class="timeline-badge danger"><i class="fa fa-ban fa-fw"></i></div>
	<div class="timeline-panel">
	@if($item->old)
		<div class="collapse" id="collapse1_{{ $item->serverId }}_{{ $item->id }}">
		@endif
		<div class="timeline-heading">
			<h4 class="timeline-title">{{ ucfirst(trans('app.banned')) }}</h4>
			<p>
				<small class="text-muted" data-toggle="tooltip" data-placement="top" title="{{ $item->created_at }}"><i class="fa fa-clock-o"></i> {{ $item->created_at->diffForHumans() }}</small>
				<small class="text-muted"><i class="fa fa-user"></i> {{ $item->actor->name }}</small>
				<small class="text-muted"><i class="fa fa-server"></i> {{ $item->server }}</small>
			</p>
		</div>
		<div class="timeline-body">
			@if($item->reason)
			{{ ucfirst(trans('app.reason')) }}: {{ $item->reason }}
			@endif
			<br />
			@if($item->expires->timestamp == 0)
			{{ trans('app.noExpire') }}
			@else
			{{ ucfirst(trans('app.expires')) }} {{ $item->expires->diffForHumans() }}.
			<br /><br />
			
			<div class="progress">
				<div class="progress-bar" role="progressbar" aria-valuenow="{{ timePasedToPercent($item->expires, $item->created) }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ timePasedToPercent($item->expires, $item->created) }}%;">
					{{ timePasedToPercent($item->expires, $item->created) }}%
				</div>
			</div>
			@endif

			@if(isset($admin) && $admin)
			<hr />
			<a href="{{ url('/admin/bans/'.$item->serverId.'/'.$item->id) }}" class="btn btn-default"><i class="fa fa-edit"></i></a>
			@endif
		</div>
		@if($item->old)
		<br /></div>
		<a data-toggle="collapse" href="#collapse1_{{ $item->serverId }}_{{ $item->id }}" aria-expanded="false" aria-controls="collapse_{{ $item->serverId }}_{{ $item->id }}">
  			{{ trans('app.toggleDetails') }}
		</a><br />
		@endif
	</div>
</li>
@elseif(get_class($item) == "App\PlayerBanRecord")
<li class="timeline-inverted">
	<div class="timeline-badge success"><i class="fa fa-ban fa-fw"></i></div>
	<div class="timeline-panel">
		@if($item->old)
		<div class="collapse" id="collapse2_{{ $item->serverId }}_{{ $item->id }}">
		@endif
			<div class="timeline-heading">
				<h4 class="timeline-title"><s>{{ ucfirst(trans('app.banned')) }}</s></h4>
				<p>
					<small class="text-muted" data-toggle="tooltip" data-placement="top" title="{{ $item->created_at }}"><i class="fa fa-clock-o"></i> {{ $item->created_at->diffForHumans() }}</small>
					<small class="text-muted"><i class="fa fa-user"></i> {{ $item->pastActor->name }}</small>
					<small class="text-muted"><i class="fa fa-server"></i> {{ $item->server }}</small>
				</p>
			</div>
			<div class="timeline-body">
				@if($item->reason)
				{{ ucfirst(trans('app.reason')) }}: {{ $item->reason }}
				@endif
				<br />
				@if($item->duration != null)<p>{{ trans('app.lastedFor', ['duration' => $item->duration]) }}</p>@endif
				<strong>{{ trans('app.unbannedBy', ['time' => $item->created->diffForHumans(), 'actor' => $item->actor->name]) }}</strong>

				@if(isset($admin) && $admin)
				<hr />
				{!! Form::open(array('url' => '/admin/ban-records/' . $item->serverId . '/' . $item->id)) !!}
				{!! Form::hidden('_method', 'DELETE') !!}
				{!! Form::submit(trans('app.remove'), array('class' => 'btn btn-warning confirmDelete')) !!}
				{!! Form::close() !!}
				@endif
			</div>
		@if($item->old)
		<br /></div>
		<a data-toggle="collapse" href="#collapse2_{{ $item->serverId }}_{{ $item->id }}" aria-expanded="false" aria-controls="collapse_{{ $item->serverId }}_{{ $item->id }}">
  			{{ trans('app.toggleDetails') }}
		</a><br />
		@endif
	</div>
</li>
@elseif(get_class($item) == "App\PlayerMute")
<li class="timeline">
	<div class="timeline-badge danger"><i class="fa fa-microphone-slash fa-fw"></i></div>
	<div class="timeline-panel">
	@if($item->old)
		<div class="collapse" id="collapse3_{{ $item->serverId }}_{{ $item->id }}">
		@endif
		<div class="timeline-heading">
			<h4 class="timeline-title">{{ ucfirst(trans('app.muted')) }}</h4>
			<p>
				<small class="text-muted" data-toggle="tooltip" data-placement="top" title="{{ $item->created_at }}"><i class="fa fa-clock-o"></i> {{ $item->created_at->diffForHumans() }}</small>
				<small class="text-muted"><i class="fa fa-user"></i> {{ $item->actor->name }}</small>
				<small class="text-muted"><i class="fa fa-server"></i> {{ $item->server }}</small>
			</p>
		</div>
		<div class="timeline-body">
			@if($item->reason)
			{{ ucfirst(trans('app.reason')) }}: {{ $item->reason }}
			@endif
			<br />
			@if($item->expires->timestamp == 0)
			{{ trans('app.noExpire') }}
			@else
			{{ ucfirst(trans('app.expires')) }} {{ $item->expires->diffForHumans() }}.
			<br /><br />

			<div class="progress">
				<div class="progress-bar" role="progressbar" aria-valuenow="{{ timePasedToPercent($item->expires, $item->created) }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ timePasedToPercent($item->expires, $item->created) }}%;">
					{{ timePasedToPercent($item->expires, $item->created) }}%
				</div>
			</div>
			@endif

			@if(isset($admin) && $admin)
			<hr />
			<a href="{{ url('/admin/mutes/'.$item->serverId.'/'.$item->id) }}" class="btn btn-default"><i class="fa fa-edit"></i></a>
			@endif
		</div>
		@if($item->old)
		<br /></div>
		<a data-toggle="collapse" href="#collapse3_{{ $item->serverId }}_{{ $item->id }}" aria-expanded="false" aria-controls="collapse_{{ $item->serverId }}_{{ $item->id }}">
  			{{ trans('app.toggleDetails') }}
		</a><br />
		@endif
	</div>
</li>
@elseif(get_class($item) == "App\PlayerMuteRecord")
<li class="timeline-inverted">
	<div class="timeline-badge success"><i class="fa fa-microphone-slash fa-fw"></i></div>
	<div class="timeline-panel">
	@if($item->old)
		<div class="collapse" id="collapse4_{{ $item->serverId }}_{{ $item->id }}">
		@endif
		<div class="timeline-heading">
			<h4 class="timeline-title"><s>{{ ucfirst(trans('app.muted')) }}</s></h4>
			<p>
				<small class="text-muted" data-toggle="tooltip" data-placement="top" title="{{ $item->created_at }}"><i class="fa fa-clock-o"></i> {{ $item->created_at->diffForHumans() }}</small>
				<small class="text-muted"><i class="fa fa-user"></i> {{ $item->pastActor->name }}</small>
				<small class="text-muted"><i class="fa fa-server"></i> {{ $item->server }}</small>
			</p>
		</div>
		<div class="timeline-body">
			@if($item->reason)
			{{ ucfirst(trans('app.reason')) }}: {{ $item->reason }}
			@endif
			<br />
			@if($item->duration != null)<p>{{ trans('app.lastedFor', ['duration' => $item->duration]) }}</p>@endif
			<strong>{{ trans('app.unmutedBy', ['time' => $item->created->diffForHumans(), 'actor' => $item->actor->name]) }}</strong>

			@if(isset($admin) && $admin)
			<hr />
			{!! Form::open(array('url' => '/admin/mute-records/' . $item->serverId  . '/' . $item->id)) !!}
			{!! Form::hidden('_method', 'DELETE') !!}
			{!! Form::submit(trans('app.remove'), array('class' => 'btn btn-warning confirmDelete')) !!}
			{!! Form::close() !!}
			@endif
		</div>
		@if($item->old)
		<br /></div>
		<a data-toggle="collapse" href="#collapse4_{{ $item->serverId }}_{{ $item->id }}" aria-expanded="false" aria-controls="collapse_{{ $item->serverId }}_{{ $item->id }}">
  			{{ trans('app.toggleDetails') }}
		</a><br />
		@endif
	</div>
</li>
@elseif(get_class($item) == "App\PlayerNote")
<li class="timeline">
	<div class="timeline-badge info"><i class="fa fa-paperclip fa-fw"></i></div>
	<div class="timeline-panel">
	@if($item->old)
		<div class="collapse" id="collapse5_{{ $item->serverId }}_{{ $item->id }}">
		@endif
		<div class="timeline-heading">
			<h4 class="timeline-title">{{ ucfirst(trans('app.noteAdded')) }}</h4>
			<p>
				<small class="text-muted" data-toggle="tooltip" data-placement="top" title="{{ $item->created_at }}"><i class="fa fa-clock-o"></i> {{ $item->created_at->diffForHumans() }}</small>
				<small class="text-muted"><i class="fa fa-user"></i> {{ $item->actor->name }}</small>
				<small class="text-muted"><i class="fa fa-server"></i> {{ $item->server }}</small>
			</p>
		</div>
		<div class="timeline-body">
			<pre>{{ $item->message }}</pre>
			@if(isset($admin) && $admin)
			<hr />
			<a href="{{ url('/admin/notes/'.$item->serverId.'/'.$item->id) }}" class="btn btn-default"><i class="fa fa-edit"></i></a>
			@endif
		</div>
		@if($item->old)
		<br /></div>
		<a data-toggle="collapse" href="#collapse5_{{ $item->serverId }}_{{ $item->id }}" aria-expanded="false" aria-controls="collapse_{{ $item->serverId }}_{{ $item->id }}">
  			{{ trans('app.toggleDetails') }}
		</a><br />
		@endif
	</div>
</li>
@elseif(get_class($item) == "App\PlayerWarning")
<li class="timeline">
	<div class="timeline-badge warning"><i class="fa fa-comment fa-fw"></i></div>
	<div class="timeline-panel">
	@if($item->old)
		<div class="collapse" id="collapse6_{{ $item->serverId }}_{{ $item->id }}">
		@endif
		<div class="timeline-heading">
			<h4 class="timeline-title">{{ ucfirst(trans('app.warned')) }}</h4>
			<p>
				<small class="text-muted" data-toggle="tooltip" data-placement="top" title="{{ $item->created_at }}"><i class="fa fa-clock-o"></i> {{ $item->created_at->diffForHumans() }}</small>
				<small class="text-muted"><i class="fa fa-user"></i> {{ $item->actor->name }}</small>
				<small class="text-muted"><i class="fa fa-server"></i> {{ $item->server }}</small>
			</p>
		</div>
		<div class="timeline-body">
			<pre>{{ $item->reason }}</pre>
			@if(isset($admin) && $admin)
			<hr />
			<a href="{{ url('/admin/warnings/'.$item->serverId.'/'.$item->id) }}" class="btn btn-default"><i class="fa fa-edit"></i></a>
			@endif
		</div>
		@if($item->old)
		<br /></div>
		<a data-toggle="collapse" href="#collapse6_{{ $item->serverId }}_{{ $item->id }}" aria-expanded="false" aria-controls="collapse_{{ $item->serverId }}_{{ $item->id }}">
  			{{ trans('app.toggleDetails') }}
		</a><br />
		@endif
	</div>
</li>
@elseif(get_class($item) == "App\PlayerKick")
<li class="timeline">
	<div class="timeline-badge info"><i class="fa fa-user-times fa-fw"></i></div>
	<div class="timeline-panel">
	@if($item->old)
		<div class="collapse" id="collapse7_{{ $item->serverId }}_{{ $item->id }}">
		@endif
		<div class="timeline-heading">
			<h4 class="timeline-title">{{ trans('app.kicked') }}</h4>
			<p>
				<small class="text-muted" data-toggle="tooltip" data-placement="top" title="{{ $item->created_at }}"><i class="fa fa-clock-o"></i> {{ $item->created_at->diffForHumans() }}</small>
				<small class="text-muted"><i class="fa fa-user"></i> {{ $item->actor->name }}</small>
				<small class="text-muted"><i class="fa fa-server"></i> {{ $item->server }}</small>
			</p>
		</div>
		<div class="timeline-body">
			@if($item->reason)
			{{ ucfirst(trans('app.reason')) }}: {{ $item->reason }}
			@endif

			@if(isset($admin) && $admin)
			<hr />
			{!! Form::open(array('url' => '/admin/kicks/' . $item->serverId  . '/' . $item->id)) !!}
			{!! Form::hidden('_method', 'DELETE') !!}
			{!! Form::submit(trans('app.remove'), array('class' => 'btn btn-warning confirmDelete')) !!}
			{!! Form::close() !!}
			@endif
		</div>
		@if($item->old)
		<br /></div>
		<a data-toggle="collapse" href="#collapse7_{{ $item->serverId }}_{{ $item->id }}" aria-expanded="false" aria-controls="collapse_{{ $item->serverId }}_{{ $item->id }}">
  			{{ trans('app.toggleDetails') }}
		</a><br />
		@endif
	</div>
</li>
@endif

application/resources/views/partials/validationErrors.blade.php
@if (isset($errors) && count($errors) > 0)
<div class="alert alert-danger">
	<strong>{{ trans('app.whoops') }}</strong> {{ trans('app.inputErrors') }}<br><br>
	{!! HTML::ul($errors->all()) !!}
</div>
@endif